
package jvproject;

import java.awt.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


public class Mylogin extends javax.swing.JFrame {

    public Mylogin() {
        initComponents();
        piclabel.setIcon(new ImageIcon(".\\pictures\\fitpic.jpg"));
        Tuser.setText("anix");
        Tpass.setText("APK2001");
        //jLabel8.setIcon(new ImageIcon(".\\pictures\\tesing\\k.jpg"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        loginPanl = new javax.swing.JPanel();
        piclabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tuser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Tpass = new javax.swing.JTextField();
        buttnpnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(854, 567));
        setResizable(false);

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 204, 255));
        kGradientPanel2.setkGradientFocus(550);
        kGradientPanel2.setkStartColor(new java.awt.Color(204, 0, 255));

        loginPanl.setBackground(new java.awt.Color(255, 255, 255));
        loginPanl.setMaximumSize(new java.awt.Dimension(726, 371));
        loginPanl.setMinimumSize(new java.awt.Dimension(726, 371));
        loginPanl.setNextFocusableComponent(loginPanl);

        piclabel.setBackground(new java.awt.Color(204, 255, 255));
        piclabel.setMaximumSize(new java.awt.Dimension(392, 330));
        piclabel.setMinimumSize(new java.awt.Dimension(392, 330));
        piclabel.setPreferredSize(new java.awt.Dimension(392, 330));

        jLabel1.setFont(new java.awt.Font("Roboto Lt", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("USER LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME");

        Tuser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tuser.setToolTipText("");
        Tuser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Tuser.setSelectionColor(new java.awt.Color(102, 102, 255));
        Tuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TuserFocusLost(evt);
            }
        });
        Tuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuserMouseClicked(evt);
            }
        });
        Tuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TuserActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Password");

        Tpass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Tpass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        Tpass.setSelectionColor(new java.awt.Color(102, 102, 255));
        Tpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TpassFocusLost(evt);
            }
        });
        Tpass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TpassMouseClicked(evt);
            }
        });

        buttnpnl.setBackground(new java.awt.Color(153, 153, 255));
        buttnpnl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttnpnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttnpnlMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttnpnlMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttnpnlMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sign in");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout buttnpnlLayout = new javax.swing.GroupLayout(buttnpnl);
        buttnpnl.setLayout(buttnpnlLayout);
        buttnpnlLayout.setHorizontalGroup(
            buttnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttnpnlLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        buttnpnlLayout.setVerticalGroup(
            buttnpnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttnpnlLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(9, 9, 9))
        );

        jLabel6.setText("You are not a member?");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 255));
        jLabel7.setText("Sign up");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });

        javax.swing.GroupLayout loginPanlLayout = new javax.swing.GroupLayout(loginPanl);
        loginPanl.setLayout(loginPanlLayout);
        loginPanlLayout.setHorizontalGroup(
            loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanlLayout.createSequentialGroup()
                .addComponent(piclabel, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanlLayout.createSequentialGroup()
                            .addGroup(loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginPanlLayout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(54, 54, 54))
                        .addComponent(Tuser)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tpass)
                        .addComponent(buttnpnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(loginPanlLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51))
        );
        loginPanlLayout.setVerticalGroup(
            loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(piclabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addGroup(loginPanlLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(Tuser, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(Tpass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(buttnpnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginPanlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Source Code Pro Black", 0, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("TRAV");

        jLabel9.setFont(new java.awt.Font("Source Code Pro Black", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("GO");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(loginPanl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(loginPanl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jLabel7.setForeground(new Color(204,102,255));
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(new Color(153,153,255));
    }//GEN-LAST:event_jLabel7MouseExited

    private void buttnpnlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnpnlMouseEntered
        buttnpnl.setBackground(new Color(163,163,255));
    }//GEN-LAST:event_buttnpnlMouseEntered

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        Myregistr mg = new Myregistr();
        mg.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void buttnpnlMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnpnlMouseExited
        buttnpnl.setBackground(new Color(153,153,255));
    }//GEN-LAST:event_buttnpnlMouseExited

    private void buttnpnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttnpnlMouseClicked
        if("".equals(Tuser.getText()) || "".equals(Tpass.getText())){
            caution cau = new caution(" Fields are empty please insert informations ");
          cau.setVisible(true);
//JOptionPane.showMessageDialog(null, "Fields are empty please insert informations ");
        }else{
            PreparedStatement ps;
            ResultSet rs;
            String userl=Tuser.getText();
            String passl=Tpass.getText();
            String query="SELECT * FROM jvproject.project_users WHERE username=? and password=?";
        try{
            ps = project_db.getConnectio().prepareStatement(query);
            ps.setString(1, userl);
            ps.setString(2, passl);
            rs = ps.executeQuery();
            if(rs.next()){
               // Account acc = new Account(userl);
               //acc.setVisible(true);
               Loading ldg = new Loading(userl);
               ldg.setVisible(true);
               this.dispose();
            }else{
                //JOptionPane.showMessageDialog(null, "You don't have an account ");
                caution cau = new caution(" You don't have an account  ");
                cau.setVisible(true);
            }
        }catch(Exception e){
            //System.out.println("connection errors");
            System.out.println(e.getMessage());
        }
        }
        
        
    }//GEN-LAST:event_buttnpnlMouseClicked

    private void TuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuserMouseClicked
        
       
    }//GEN-LAST:event_TuserMouseClicked

    private void TpassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TpassMouseClicked

    }//GEN-LAST:event_TpassMouseClicked

    private void TuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TuserFocusGained
        Tuser.setBackground(new Color(246,246,246));
        Tuser.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }//GEN-LAST:event_TuserFocusGained

    private void TuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TuserFocusLost
        Tuser.setBackground(Color.white);
        Tuser.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }//GEN-LAST:event_TuserFocusLost

    private void TpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpassFocusGained
        Tpass.setBackground(new Color(246,246,246));
        Tpass.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
    }//GEN-LAST:event_TpassFocusGained

    private void TpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TpassFocusLost
        Tpass.setBackground(new Color(255,255,255));
        Tpass.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, Color.BLACK));
    }//GEN-LAST:event_TpassFocusLost

    private void TuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TuserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mylogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mylogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mylogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mylogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mylogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tpass;
    private javax.swing.JTextField Tuser;
    private javax.swing.JPanel buttnpnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JPanel loginPanl;
    private javax.swing.JLabel piclabel;
    // End of variables declaration//GEN-END:variables
}
