package jvproject;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.image.BufferedImage;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author as
 */
public class plot extends javax.swing.JPanel {

    String Id="";
    public plot(String Id) {
        initComponents();
        this.Id=Id;
    }
    public void paint(Graphics g) {
		Graphics2D g2 = (Graphics2D) g;
		
                //gd.drawLine(50, 180, 620, 180);
                
                g2.setStroke(new BasicStroke(3));
                g2.draw(new Line2D.Float(60, 180, 700, 180));
                Color coleur[]={new Color(255,204,204),new Color(244,172,248),new Color(153,255,153),new Color(255,140,140),new Color(102,195,204),new Color(150,151,176),new Color(246,209,140),new Color(218,218,205),new Color(255,153,153),new Color(199,67,67),new Color(143,255,221),new Color(0,102,102)};
                String delim[] = {"2022-1-1","2022-2-1","2022-3-1","2022-4-1","2022-5-1","2022-6-1","2022-7-1","2022-8-1","2022-9-1","2022-10-1","2022-11-1","2022-12-1"};
                String delim2[] = {"2022-1-31","2022-2-28","2022-3-31","2022-4-30","2022-5-31","2022-6-30","2022-7-31","2022-8-31","2022-9-30","2022-10-31","2022-11-30","2022-12-31"};
                int value[] = new int[12];
                String months[]={"Jan","Feb","Mar","Apr","Mai","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};
                
                PreparedStatement ps;
       
                ResultSet rs;
                for(int i=0;i<12;i++){
                    String query="select count(*) from reservation where us_ID="+Id+" AND (date_depart between '";
                    query=query+delim[i]+"' AND '"+delim2[i]+"');";
                    try{
                        //ps.setString(1, id);
                        ps = project_db.getConnectio().prepareStatement(query);  
                        rs = ps.executeQuery();
                        if(rs.next()){
                           value[i]=(Integer.parseInt(rs.getString(1)));
                        }else{
                                JOptionPane.showMessageDialog(null, "You don't have an account ");
                        }
                     }catch(Exception e){
                            //System.out.println("connection errors");
                            System.out.println(e.getMessage());
                             }
                }
                
                
                
                
                
                g2.setPaint(Color.BLACK);
                g2.setFont(new Font("Segoe UI", Font.PLAIN, 20));
                g2.drawString("Number Reservations per month in 2022",190 , 50);
                
                for(int i=0;i<12;i++){
                    g2.setPaint(coleur[i]);
                    g2.fillRect((85+(50*i)), (180-(value[i]*7)-1), 40, (value[i]*7));
                    g2.setPaint(Color.BLACK);
                    g2.setFont(new Font("", Font.PLAIN, 15));
                    g2.drawString(months[i], (95+(50*i)), 200);
                    g2.setFont(new Font("", Font.BOLD, 13));
                    g2.drawString(""+value[i], (101+(50*i)), (180-(value[i]*7)-5));
   
                }
                for(int i=0;i<11;i++){
                    g2.setPaint(Color.BLACK);
                    g2.setStroke(new BasicStroke(2));
                    g2.drawLine((105+(50*i)),(180-(value[i]*7)-1) , (105+(50*(i+1))),(180-(value[i+1]*7)-1) );
                }
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
